# Generated by Django 4.0.2 on 2022-02-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_user',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('mid_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('mail', models.CharField(max_length=50, unique=True)),
                ('phone', models.BigIntegerField(default=None)),
                ('username', models.CharField(default=None, max_length=30, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_content_writer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='following_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=30)),
                ('following', models.ManyToManyField(to='backend.register_user')),
            ],
            options={
                'db_table': 'follower_table',
            },
        ),
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(default='-', max_length=6)),
                ('file_name', models.CharField(default='-', max_length=50)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.register_user', verbose_name='user_unique_id')),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
        migrations.CreateModel(
            name='extra_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(max_length=300)),
                ('insta', models.URLField(max_length=300)),
                ('twitter', models.URLField(max_length=300)),
                ('website', models.URLField(max_length=300)),
                ('profile', models.CharField(max_length=200)),
                ('other_link', models.URLField(max_length=300)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.register_user', verbose_name='user_unique_id')),
            ],
        ),
    ]
