# Generated by Django 4.0.1 on 2022-02-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_register_user_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='mid_name',
        ),
    ]
