# Generated by Django 4.0.2 on 2022-02-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_register_user_mid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='is_appropriate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='file_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='file_type',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
