# Generated by Django 4.0.2 on 2022-02-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_file_upload_is_appropriate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='file_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
