# Generated by Django 4.0.2 on 2022-02-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_file_upload_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='category',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
